# Arquivo: docker-compose.yml
version: '3.8'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - sgcpd-network
    env_file:
      - ./client/.env.template

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/sgcpd_db
    depends_on:
      - db
    networks:
      - sgcpd-network
    env_file:
      - ./server/.env.template

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sgcpd_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - sgcpd-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d sgcpd_db"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  sgcpd-network:
    driver: bridge

volumes:
  postgres-data: